// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Soundgenius.Data;

namespace Soundgenius.Migrations
{
    [DbContext(typeof(SoundgeniusDB))]
    [Migration("20200629173930_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Soundgenius.Models.AlbumFaixas", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlbumFK")
                        .HasColumnType("int");

                    b.Property<int>("FaixaFK")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AlbumFK");

                    b.HasIndex("FaixaFK");

                    b.ToTable("AlbumFaixas");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AlbumFK = 1,
                            FaixaFK = 1
                        },
                        new
                        {
                            ID = 2,
                            AlbumFK = 2,
                            FaixaFK = 2
                        },
                        new
                        {
                            ID = 3,
                            AlbumFK = 3,
                            FaixaFK = 3
                        },
                        new
                        {
                            ID = 4,
                            AlbumFK = 4,
                            FaixaFK = 4
                        },
                        new
                        {
                            ID = 5,
                            AlbumFK = 5,
                            FaixaFK = 5
                        },
                        new
                        {
                            ID = 6,
                            AlbumFK = 6,
                            FaixaFK = 6
                        },
                        new
                        {
                            ID = 7,
                            AlbumFK = 7,
                            FaixaFK = 7
                        },
                        new
                        {
                            ID = 8,
                            AlbumFK = 8,
                            FaixaFK = 8
                        },
                        new
                        {
                            ID = 9,
                            AlbumFK = 9,
                            FaixaFK = 10
                        },
                        new
                        {
                            ID = 10,
                            AlbumFK = 7,
                            FaixaFK = 9
                        });
                });

            modelBuilder.Entity("Soundgenius.Models.Albuns", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArtistaFK")
                        .HasColumnType("int");

                    b.Property<string>("FicheiroImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ArtistaFK");

                    b.ToTable("Albuns");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ArtistaFK = 1,
                            FicheiroImg = "MTV Unplugged",
                            Genero = "Grunge",
                            Titulo = "MTV Unplugged"
                        },
                        new
                        {
                            ID = 2,
                            ArtistaFK = 1,
                            FicheiroImg = "Bleach",
                            Genero = "Grunge",
                            Titulo = "Bleach"
                        },
                        new
                        {
                            ID = 3,
                            ArtistaFK = 1,
                            FicheiroImg = "Nevermind",
                            Genero = "Grunge",
                            Titulo = "Nevermind"
                        },
                        new
                        {
                            ID = 4,
                            ArtistaFK = 2,
                            FicheiroImg = "The color and the shape",
                            Genero = "Rock Alternativo ",
                            Titulo = "The color and the shape"
                        },
                        new
                        {
                            ID = 5,
                            ArtistaFK = 2,
                            FicheiroImg = "In Your Honor",
                            Genero = "Rock Alternativo ",
                            Titulo = " In Your Honor"
                        },
                        new
                        {
                            ID = 6,
                            ArtistaFK = 2,
                            FicheiroImg = "Foo Fighters Echoes, Silence, Patience & Grace",
                            Genero = "Rock Alternativo ",
                            Titulo = "Foo Fighters Echoes, Silence, Patience & Grace"
                        },
                        new
                        {
                            ID = 7,
                            ArtistaFK = 3,
                            FicheiroImg = "Testing",
                            Genero = "Hip hop",
                            Titulo = "Testing"
                        },
                        new
                        {
                            ID = 8,
                            ArtistaFK = 3,
                            FicheiroImg = "Long. Live. ASAP",
                            Genero = "Hip hop",
                            Titulo = "Long. Live. ASAP"
                        },
                        new
                        {
                            ID = 9,
                            ArtistaFK = 4,
                            FicheiroImg = "goodbye & good riddance",
                            Genero = "Hip hop ",
                            Titulo = "goodbye & good riddance"
                        });
                });

            modelBuilder.Entity("Soundgenius.Models.Artista", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FicheiroImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)")
                        .HasMaxLength(40);

                    b.Property<string>("Sexo")
                        .HasColumnType("nvarchar(1)")
                        .HasMaxLength(1);

                    b.HasKey("ID");

                    b.ToTable("Artista");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FicheiroImg = "Nirvana",
                            Nome = "Nirvana",
                            Sexo = "M"
                        },
                        new
                        {
                            ID = 2,
                            FicheiroImg = "Foo Figthers",
                            Nome = "Foo Figthers",
                            Sexo = "M"
                        },
                        new
                        {
                            ID = 3,
                            FicheiroImg = "Asap Rocky",
                            Nome = "Asap Rocky",
                            Sexo = "M"
                        },
                        new
                        {
                            ID = 4,
                            FicheiroImg = "Juice wrld",
                            Nome = "Juice wrld",
                            Sexo = "M"
                        });
                });

            modelBuilder.Entity("Soundgenius.Models.Faixas", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FicheiroImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Faixas");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            FicheiroImg = "MTV Unplugged",
                            Genero = "Grunge",
                            Titulo = "The man who sold the word"
                        },
                        new
                        {
                            ID = 2,
                            FicheiroImg = "Bleach",
                            Genero = "Grunge",
                            Titulo = "About a girl"
                        },
                        new
                        {
                            ID = 3,
                            FicheiroImg = "Nevermind",
                            Genero = "Grunge",
                            Titulo = "come as you are"
                        },
                        new
                        {
                            ID = 4,
                            FicheiroImg = "The color and the shape",
                            Genero = "Rock Alternativo",
                            Titulo = "Everlong"
                        },
                        new
                        {
                            ID = 5,
                            FicheiroImg = "In Your Honor",
                            Genero = "Rock Alternativo",
                            Titulo = "Best of you"
                        },
                        new
                        {
                            ID = 6,
                            FicheiroImg = "Testing",
                            Genero = "Rock Alternativo",
                            Titulo = "Pretender"
                        },
                        new
                        {
                            ID = 7,
                            FicheiroImg = "dsfhshdfs",
                            Genero = "Hip hop",
                            Titulo = "Fukk Sleep"
                        },
                        new
                        {
                            ID = 8,
                            FicheiroImg = "Long. Live. ASAP",
                            Genero = "Hip hop",
                            Titulo = "PMW"
                        },
                        new
                        {
                            ID = 9,
                            FicheiroImg = "Long. Live. ASAP",
                            Genero = "Hip hop",
                            Titulo = "lVL"
                        },
                        new
                        {
                            ID = 10,
                            FicheiroImg = "goodbye & good riddance",
                            Genero = "Hip hop",
                            Titulo = "Wasted"
                        });
                });

            modelBuilder.Entity("Soundgenius.Models.AlbumFaixas", b =>
                {
                    b.HasOne("Soundgenius.Models.Albuns", "Album")
                        .WithMany("AlbumFaixas")
                        .HasForeignKey("AlbumFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Soundgenius.Models.Faixas", "Faixa")
                        .WithMany("AlbumFaixas")
                        .HasForeignKey("FaixaFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Soundgenius.Models.Albuns", b =>
                {
                    b.HasOne("Soundgenius.Models.Artista", "Artista")
                        .WithMany("Albuns")
                        .HasForeignKey("ArtistaFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
