// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Soundgenius.Data;

namespace Soundgenius.Migrations
{
    [DbContext(typeof(SoundgeniusDB))]
    partial class SoundgeniusDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Soundgenius.Models.AlbumFaixas", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlbumFK")
                        .HasColumnType("int");

                    b.Property<int>("FaixaFK")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AlbumFK");

                    b.HasIndex("FaixaFK");

                    b.ToTable("AlbumFaixas");
                });

            modelBuilder.Entity("Soundgenius.Models.Albuns", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Autor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FicheiroImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilizadorFK")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("UtilizadorFK");

                    b.ToTable("Albuns");
                });

            modelBuilder.Entity("Soundgenius.Models.Faixas", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Autor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FicheiroImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Faixas");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Autor = "Nirvana",
                            FicheiroImg = "dsfhshdfs",
                            Genero = "Grunge",
                            Titulo = "The man who sold the word"
                        },
                        new
                        {
                            ID = 2,
                            Autor = "Nirvana",
                            FicheiroImg = "dsfhshdfs",
                            Genero = "Grunge",
                            Titulo = "About a girl"
                        },
                        new
                        {
                            ID = 3,
                            Autor = "Nirvana",
                            FicheiroImg = "dsfhshdfs",
                            Genero = "Grunge",
                            Titulo = "you know you are right"
                        },
                        new
                        {
                            ID = 4,
                            Autor = "Foo Figthers",
                            FicheiroImg = "dsfhshdfs",
                            Genero = "Rock Alternativo",
                            Titulo = "Everlong"
                        },
                        new
                        {
                            ID = 5,
                            Autor = "Foo Figthers",
                            FicheiroImg = "dsfhshdfs",
                            Genero = "Rock Alternativo",
                            Titulo = "Best of you"
                        },
                        new
                        {
                            ID = 6,
                            Autor = "Foo Figthers",
                            FicheiroImg = "dsfhshdfs",
                            Genero = "Rock Alternativo",
                            Titulo = "Pretender"
                        },
                        new
                        {
                            ID = 7,
                            Autor = "Asap Rocky",
                            FicheiroImg = "dsfhshdfs",
                            Genero = "Hip hop",
                            Titulo = "Peso"
                        },
                        new
                        {
                            ID = 8,
                            Autor = "Asap Rocky",
                            FicheiroImg = "dsfhshdfs",
                            Genero = "Hip hop",
                            Titulo = "PMW"
                        },
                        new
                        {
                            ID = 9,
                            Autor = "Asap Rocky",
                            FicheiroImg = "dsfhshdfs",
                            Genero = "Hip hop",
                            Titulo = "lVL"
                        },
                        new
                        {
                            ID = 10,
                            Autor = "Juice world",
                            FicheiroImg = "dsfhshdfs",
                            Genero = "Hip hop",
                            Titulo = "Bandid"
                        });
                });

            modelBuilder.Entity("Soundgenius.Models.Utilizador", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Autor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContaFacebook")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusicaPerf")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Utilizador");
                });

            modelBuilder.Entity("Soundgenius.Models.AlbumFaixas", b =>
                {
                    b.HasOne("Soundgenius.Models.Albuns", "Album")
                        .WithMany("AlbumFaixas")
                        .HasForeignKey("AlbumFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Soundgenius.Models.Faixas", "Faixa")
                        .WithMany("AlbumFaixas")
                        .HasForeignKey("FaixaFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Soundgenius.Models.Albuns", b =>
                {
                    b.HasOne("Soundgenius.Models.Utilizador", "Utilizador")
                        .WithMany("ListaAlbum")
                        .HasForeignKey("UtilizadorFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
